---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tsibbledata)
library(tidyverse)
library(lubridate)
library(tsibble)
library(dplyr)
```

```{r}

specialties_raw <- read_csv("non_covid/inpatient_and_daycase_by_nhs_board_of_treatment_and_specialty.csv") %>%
 janitor:: clean_names()

hb <- read_csv("covid_data/hb14_hb19.csv") %>% janitor::clean_names()

hospitals <- read_csv("general/current-hospital_flagged20211216.csv") %>% 
  janitor::clean_names() %>% 
  select(location, location_name)

```

```{r}

specialties <- specialties_raw %>% 
  inner_join(hb, "hb") %>% 
  inner_join(hospitals, "location") %>% 
  select(-ends_with("qf"), -hb, - specialty) %>% 
  select(quarter, hb_name, location, location_name, everything()) %>% 
  mutate(year = as.numeric(str_sub(quarter,1, 4)), .before = quarter) %>% 
  mutate(is_covid_year = case_when(
    year >= 2020 ~ TRUE,
    year < 2020 ~ FALSE
  ))
  # mutate(quarter = str_sub(quarter, -2, -1))

specialties

```

```{r}

total_admissions <- specialties %>% 
  group_by(is_covid_year) %>% 
  filter(admission_type == "All Inpatients and Day cases") %>% 
  summarise(total_admissions = sum(episodes)) %>% 
  pull(total_admissions)


change_in_specialties <- specialties %>% 
 # filter(hb_name == "NHS Ayrshire and Arran") %>% #for input 
  group_by(specialty_name, is_covid_year) %>% 
  summarise(total_episodes = sum(episodes)) %>% 
  pivot_wider(names_from = is_covid_year, values_from = total_episodes) %>% 
  rename("covid_year" = "TRUE", "pre_covid_year" = "FALSE") %>% 
  mutate(pre_covid_year_prop = pre_covid_year / total_admissions[1],
         covid_year_prop = covid_year / total_admissions[2],
         percentage_change = ((covid_year_prop / pre_covid_year_prop) - 1) * 100)
 

change_in_specialties %>% 
  arrange(desc(percentage_change)) %>% 
  head(5) %>% 
  filter(percentage_change > 0) %>% 
  arrange(desc(percentage_change)) %>% 
  ggplot(aes(x = reorder(specialty_name, percentage_change, decreasing = TRUE),
             y = percentage_change)) +
  geom_col() +
  theme_classic() +
  scale_y_continuous(expand = c(0,0)) +
  theme(axis.title.x = element_blank(),
        axis.text.x = element_text(size = 8,angle = 45, hjust = 1)) +
  labs(y = "Percentage Increase (%)",
       title = "Top 5 changes in hospital admissions (by specialty) - pre-Covid vs Covid",
       subtitle = "More than 1,000 admissions")

```




```{r}
library(reshape2)
before_after_covid <- specialties %>% 
    filter(hb_name == "NHS Ayrshire and Arran") %>% #for input 
  group_by(specialty_name, is_covid_year,hb_name) %>% 
  summarise(total_episodes = sum(episodes)) %>% 
  pivot_wider(names_from = is_covid_year, values_from = total_episodes) %>% 
  rename("covid_year" = "TRUE", "pre_covid_year" = "FALSE") %>% 
  mutate(pre_covid_year_prop = pre_covid_year / total_admissions[1],
         covid_year_prop = covid_year / total_admissions[2],
         percentage_change = ((covid_year_prop / pre_covid_year_prop) - 1) * 100) %>% 
  select(specialty_name,hb_name,pre_covid_year_prop,covid_year_prop,
percentage_change
)
  

data_mod_before_after_covid <- melt(before_after_covid,
                  measure.vars=c('pre_covid_year_prop', 'covid_year_prop')) %>% 
  arrange(desc(percentage_change)) %>% 
  filter(percentage_change > 0) %>% 
  head(10)
  
  

ggplot(data_mod_before_after_covid) +
geom_col(aes(x = reorder(specialty_name, percentage_change, decreasing = TRUE),
             y=value, color=variable, fill = variable), position = "dodge")+
  theme(axis.title.x = element_blank(),
        axis.text.x = element_text(size = 8,angle = 45, hjust = 1)) +
  scale_fill_manual(values = c("pre_covid_year_prop" = "grey", "covid_year_prop"= "red"))+
  scale_colour_manual(values = c("pre_covid_year_prop" = "grey", "covid_year_prop"= "red"))+
  labs(y = "Percentage (%)",
       title = "Top 5 changes in hospital admissions (by specialty) - pre-Covid vs Covid",
       subtitle = "y is the percentage but x is ordered by percentage changes")
  
  

```
# had one sample input hb, more than one HB? facet? too small if facet? 
tab for each HB ?? can we do that? (tabs appear as selected?)
or on it own? 
#some only had 3 +tive 


